apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-thesis-cluster-v1
  region: eu-north-1
  version: "1.32"

vpc:
  subnets:
    public:
      eu-north-1a:
        id: subnet-0f92bf3d1592b827e
      eu-north-1b:
        id: subnet-0321792ff147f408b
      eu-north-1c:
        id: subnet-0d713ffea4332a283

cloudWatch:
  clusterLogging:
    enableTypes:
      ["api", "audit", "authenticator", "controllerManager", "scheduler"]

nodeGroups:
  - name: ng-thesis
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 30
    ssh:
      allow: false
    labels:
      role: worker
      project: thesis
    tags:
      NodeGroup: thesis-ng
      Project: thesis
