apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-secrets
type: Opaque
data:
  connection-string: SG9zdD1pbnZlbnRvcnlkYi5jMWFzY215MmdnMWYuZXUtbm9ydGgtMS5yZHMuYW1hem9uYXdzLmNvbTtQT1JUPTU0MzI7RGF0YWJhc2U9aW52ZW50b3J5ZGI7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9TG92ZXJzYWZnMTU0NAo=